FROM node:22-alpine

WORKDIR /workspace/frontend/jobseeker

COPY ./frontend/jobseeker/package*.json ./
RUN npm install

COPY ./frontend/jobseeker ./
COPY ./shared ../../shared

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
