services:
  auth-service:
    build:
      context: ${AUTHSDK_PATH:-../authSDK}
      dockerfile: docker/Dockerfile
    image: auth-service:local
    pull_policy: never

  auth-webhook-worker:
    image: auth-service:local
    pull_policy: never

  auth-webhook-scheduler:
    image: auth-service:local
    pull_policy: never
